GET  http://localhost:8000/api/disabilities/
Authorization: Bearer 10|PCPLvGBg9BRSuqTh9lPOkMEHDxXMNJRQ7Q4nlYcm598cd36b
Content-Type: application/json

# {"email":"yikeber50@gmail.com",
#   "password":"yike12345"
# }